defmodule Demo.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:storage_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :byte_size, :bigint
      add :checksum, :text
      add :service_name, :text, null: false
      add :service_opts, :map, default: %{}
      add :metadata, :map, default: %{}
      add :analyzers, :map, default: %{}
      add :pending_purge, :boolean, null: false, default: false
      add :pending_analyzers, :boolean, null: false, default: false
      add :pending_variants, :boolean, null: false, default: false

      add :variant_of_blob_id,
          references(:storage_blobs,
            column: :id,
            name: "storage_blobs_variant_of_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :variant_name, :text
      add :variant_digest, :text
    end

    create table(:storage_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :blob_id,
          references(:storage_blobs,
            column: :id,
            name: "storage_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :post_id, :uuid
      add :page_id, :uuid
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_attachments) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "storage_attachments_post_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:posts) do
      add :title, :text, null: false
    end

    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_attachments) do
      modify :page_id,
             references(:pages,
               column: :id,
               name: "storage_attachments_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:pages) do
      add :title, :text, null: false
      add :image_width, :bigint
      add :image_height, :bigint
    end
  end

  def down do
    alter table(:pages) do
      remove :image_height
      remove :image_width
      remove :title
    end

    drop constraint(:storage_attachments, "storage_attachments_page_id_fkey")

    alter table(:storage_attachments) do
      modify :page_id, :uuid
    end

    drop table(:pages)

    alter table(:posts) do
      remove :title
    end

    drop constraint(:storage_attachments, "storage_attachments_post_id_fkey")

    alter table(:storage_attachments) do
      modify :post_id, :uuid
    end

    drop table(:posts)

    drop constraint(:storage_attachments, "storage_attachments_blob_id_fkey")

    drop table(:storage_attachments)

    drop constraint(:storage_blobs, "storage_blobs_variant_of_blob_id_fkey")

    drop table(:storage_blobs)
  end
end
