defmodule AshStoragePGLO.Test.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:storage_los, primary_key: false) do
      add :key, :text, null: false, primary_key: true
      add :oid, :oid, null: false
    end

    execute("""
    CREATE TRIGGER lo_manage_storage_los BEFORE UPDATE OR DELETE ON storage_los
      FOR EACH ROW EXECUTE FUNCTION lo_manage(oid);
    """)
  end

  def down do
    execute("""
    DROP TRIGGER IF EXISTS lo_manage_storage_los ON storage_los;
    """)

    drop table(:storage_los)
  end
end
